import path from 'node:path'
import type { Plugin } from 'vite'
import fs from 'node:fs'

const DEFAULT_ROUTES_DIR = 'src/routes'
const DEFAULT_OUTPUT_CLIENT = '.buna/client-routes.generated.ts'
const DEFAULT_OUTPUT_HONO = '.buna/server-routes.generated.ts'

export type BunaOptions = {
  /**
   * Relative path (from project root) to the routes directory
   * Example: 'src/routes'
   */
  routesDir?: string

  /**
   * Relative path (from project root) to the generated client routes file
   * Example: '.buna/client-routes.generated.ts'
   */
  outputClient?: string

  /**
   * Relative path (from project root) to the generated Hono routes file
   * Example: '.buna/server-routes.generated.tsx'
   */
  outputHono?: string
}

type ResolvedBunaOptions = {
  routesDir: string
  outputClient: string
  outputHono: string
}


// Helper to write files
function writeFileSafe(projectRoot: string, relPath: string, content: string) {
  const fullPath = path.resolve(projectRoot, relPath)
  const dir = path.dirname(fullPath)

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(fullPath, content, 'utf8')
}

function createGlobBase(routesDir: string): string {
  let dir = routesDir.replace(/\\/g, '/')
  dir = dir.replace(/^\.?\//, '') // remove leading "./"
  return '/' + dir.replace(/\/$/, '')
}

/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createClientFileContent(routesDir: string): string {
  const base = createGlobBase(routesDir)
  const globPattern = `${base}/**/*.{tsx,jsx,mdx}`

  return `/// <reference types="vite/client" />
  // AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import { createRouterConfigFromGlob } from '@buna/router/runtime-client'

const files = import.meta.glob('${globPattern}', { eager: true })

export const config = createRouterConfigFromGlob(files, { routesBase: '${base}' })

export const routes = config.routes
export const routeComponents = config.routeComponents
export const routesMeta = config.routesMeta
export const directoryLayers = config.directoryLayers
export const directoryOrder = config.directoryOrder
export const $router = config.$router
export type RoutingKeys = keyof typeof routeComponents
`
}

/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createHonoFileContent(routesDir: string): string {
  const base = createGlobBase(routesDir)
  const globPattern = `${base}/**/*.{tsx,jsx,mdx}`

  return `/// <reference types="vite/client" />
// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import { createHonoAppFromGlob } from '@buna/router/runtime-hono'

const files = import.meta.glob('${globPattern}', { eager: true })

const config = createHonoAppFromGlob(files, { routesBase: '${base}' })

export const honoRoutesMeta = config.routesMeta
export const honoDirectoryLayers = config.directoryLayers
export const honoDirectoryOrder = config.directoryOrder
export default config.app
`
}

function generateAll(projectRoot: string, opts: ResolvedBunaOptions) {
  const clientContent = createClientFileContent(opts.routesDir)
  writeFileSafe(projectRoot, opts.outputClient, clientContent)

  const honoContent = createHonoFileContent(opts.routesDir)
  writeFileSafe(projectRoot, opts.outputHono, honoContent)
}

export function buna(options: BunaOptions = {}): Plugin {
  let root = process.cwd()

  const resolved: ResolvedBunaOptions = {
    routesDir: options.routesDir ?? DEFAULT_ROUTES_DIR,
    outputClient: options.outputClient ?? DEFAULT_OUTPUT_CLIENT,
    outputHono: options.outputHono ?? DEFAULT_OUTPUT_HONO,
  }

  return {
    name: 'buna-plugin',

    configResolved(config) {
      root = config.root
      generateAll(root, resolved)
    },

    buildStart() {
      // In case configResolved was not enough (e.g. direct build)
      generateAll(root, resolved)
    },

    configureServer(server) {
      const watchDir = path.resolve(root, resolved.routesDir)

      const maybeGenerate = (file: string) => {
        if (file.startsWith(watchDir)) {
          generateAll(root, resolved)
        }
      }

      server.watcher.on('add', maybeGenerate)
      server.watcher.on('unlink', maybeGenerate)
      server.watcher.on('change', maybeGenerate)
    },
  }
}