import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ResolvedConfig } from 'vite'
import type { BunaConfig, ResolvedBunaConfig, } from "@buna/config"
import type { BunaRuntime } from '@buna/config'

const DEFAULT_ROUTES_DIR = 'src/routes'
const DEFAULT_SERVER_DIR = 'src/server'
const DEFAULT_OUTPUT_CLIENT = '.buna/client-routes.generated.ts'
const DEFAULT_OUTPUT_SERVER = '.buna/server-routes.generated.ts'
const DEFAULT_API_PATH = '/api'
const DEFAULT_API_FILE = 'src/server/api.ts'
const DEFAULT_OUTPUT_QUERY = '.buna/query.generated.ts'
const DEFAULT_OUTPUT_TYPES = '.buna/routes.generated.d.ts'


function filePathToPath(filePath: string): string {
  return filePath
    .replace(/\.tsx?$/g, '')
    .replace(/\.mdx?$/g, '')
    .replace(/^\/?index$/, '/')
    .replace(/\/index$/, '')
    .replace(/\[\.{3}.+\]/, '*')
    .replace(/\((.+?)\)/g, '')
    .replace(/\[(.+?)\]/g, ':$1')
    .replace(/\/\/+/g, '/')
    .replace(/^\/*/, '/'); // garante que começa com '/'
}


function resolveOptions(opts: BunaConfig = {}): ResolvedBunaConfig {
  return {
    routesDir: opts.routesDir ?? DEFAULT_ROUTES_DIR,
    serverDir: opts.serverDir ?? DEFAULT_SERVER_DIR,
    outputClient: opts.outputClient ?? DEFAULT_OUTPUT_CLIENT,
    outputHono: opts.outputHono ?? DEFAULT_OUTPUT_SERVER,
    apiFile: opts.apiFile ?? DEFAULT_API_FILE, // or src/server/api.ts in template final
    outputQuery: opts.outputQuery ?? DEFAULT_OUTPUT_QUERY,
    apiBasePath: opts.apiBasePath ?? DEFAULT_API_PATH,
    outputTypes: opts.outputTypes ?? DEFAULT_OUTPUT_TYPES,
    vite: opts.vite ?? {},
    // runtime: opts.runtime as BunaRuntime
  };
}

// Helper to write files
function writeFileSafe(projectRoot: string, relPath: string, content: string) {
  const fullPath = path.resolve(projectRoot, relPath)
  const dir = path.dirname(fullPath)

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(fullPath, content, 'utf8')
}

function createGlobBase(routesDir: string): string {
  let dir = routesDir.replace(/\\/g, '/')
  dir = dir.replace(/^\.?\//, '') // remove leading "./"
  return '/' + dir.replace(/\/$/, '')
}

function createRoutesTypesFileContent(projectRoot: string, routesDir: string): string {
  const routes: { path: string; params: string[] }[] = [];

  const absRoutesDir = path.join(projectRoot, routesDir);

  if (!fs.existsSync(absRoutesDir)) {
    return `// AUTO-GENERATED BY buna-plugin. NO ROUTES DIRECTORY FOUND.
export {};
`;
  }

  const entries: string[] = [];

  const walk = (dir: string) => {
    const dirents = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of dirents) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        continue;
      }

      const ext = path.extname(entry.name);
      if (!['.tsx', '.jsx', '.mdx'].includes(ext)) continue;

      entries.push(full);
    }
  };

  walk(absRoutesDir);

  for (const absFile of entries) {
    const relFromRoutes = path.relative(absRoutesDir, absFile).replace(/\\/g, '/');
    const routePath = filePathToPath(relFromRoutes);

    // opcional: ignorar rotas especiais que não são "pages"
    // ex: _error, _not-found, _layout etc.
    const lastSegment = routePath.split('/').pop() || '';
    if (lastSegment.startsWith('_')) {
      continue;
    }

    const paramNames: string[] = [];
    const paramRegex = /:([a-zA-Z0-9_]+)/g;
    let m: RegExpExecArray | null;
    while ((m = paramRegex.exec(routePath)) != null) {
      paramNames.push(m[1]);
    }

    routes.push({ path: routePath, params: paramNames });
  }

  if (routes.length === 0) {
    return `// AUTO-GENERATED BY buna-plugin. NO ROUTES FOUND.
export {};
`;
  }

  // Ordena para ter determinismo
  routes.sort((a, b) => a.path.localeCompare(b.path));

  const pathUnion = routes.map((r) => `'${r.path}'`).join(' | ');

  const paramsLines = routes
    .map((r) => {
      if (r.params.length === 0) {
        return `    '${r.path}': {};`;
      }
      const fields = r.params.map((p) => `${p}: string;`).join(' ');
      return `    '${r.path}': { ${fields} };`;
    })
    .join('\n');

  const searchLines = routes
    .map((r) => `    '${r.path}': Record<string, string>;`)
    .join('\n');

  return `// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import type { RouteProps, RouteComponent } from '@buna/router';
import type { HtmlEscapedString } from 'hono/utils/html';

declare module '@buna/router' {
  export type FileRoutePath =
    ${pathUnion};

  export interface FileRouteParamsMap {
${paramsLines}
  }

  export interface FileRouteSearchMap {
${searchLines}
  }

  export type FileRouteProps<P extends FileRoutePath, TExtraProps = unknown> =
    RouteProps<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>;

  export type FileRouteComponent<P extends FileRoutePath, TExtraProps = unknown> =
    RouteComponent<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>;

  export function CreateComponent<P extends FileRoutePath, TExtraProps = unknown>(
    path: P,
    render: (
      props: RouteProps<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>
    ) => HtmlEscapedString | Promise<HtmlEscapedString>,
    options?: RouteComponent<FileRouteParamsMap[P], FileRouteSearchMap[P]>
  ): RouteComponent<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>;
}
`;
}

/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createClientFileContent(routesDir: string): string {
  const base = createGlobBase(routesDir)
  const globPattern = `${base}/**/*.{tsx,jsx,mdx}`

  return `/// <reference types="vite/client" />
  // AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
  import { RouteModule } from '@buna/router/router-core'
import { createRouterConfigFromGlob } from '@buna/router/runtime-client'

const files = import.meta.glob('${globPattern}', { eager: true })  as Record<string, RouteModule>

export const config = createRouterConfigFromGlob(files, { routesBase: '${base}' })

export const routes = config.routes
export const routeComponents = config.routeComponents
export const routesMeta = config.routesMeta
export const directoryLayers = config.directoryLayers
export const directoryOrder = config.directoryOrder
export const $router = config.$router
export type RoutingKeys = keyof typeof routeComponents
`
}

/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createHonoFileContent(routesDir: string): string {
  const base = createGlobBase(routesDir)
  const globPattern = `${base}/**/*.{tsx,jsx,mdx}`

  return `/// <reference types="vite/client" />
// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import { createHonoAppFromGlob } from '@buna/router/runtime-hono'

const files = import.meta.glob('${globPattern}', { eager: true })

const config = createHonoAppFromGlob(files, { routesBase: '${base}' })

export const honoRoutesMeta = config.routesMeta
export const honoDirectoryLayers = config.directoryLayers
export const honoDirectoryOrder = config.directoryOrder
export default config.app
`
}


/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createQueryFileContent(projectRoot: string, opts: ResolvedBunaConfig): string {
  const apiRoutes = readApiRoutes(projectRoot, opts.apiFile, opts.apiBasePath);

  if (apiRoutes.length === 0) {
    return `// AUTO-GENERATED BY buna-plugin. NO API ROUTES FOUND.
export const api = {} as const;
export type ApiClient = typeof api;
`;
  }


  const header = `// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import { createFetcherStore, createMutatorStore } from '@buna/router/query';
`;

  // Group routes by first segment after /api
  const groups: Record<string, ApiRouteMeta[]> = {};

  for (const route of apiRoutes) {
    const parts = route.path.replace(/^\/+/, '').split('/'); // ['api', 'posts', ':id']
    const resource = parts[1] || 'root';

    if (!groups[resource]) groups[resource] = [];
    groups[resource].push(route);
  }

  const bodyLines: string[] = [];
  bodyLines.push('export const api = {');

  for (const [resource, routes] of Object.entries(groups)) {
    bodyLines.push(`  ${resource}: {`);

    for (const route of routes) {
      const parts = route.path.replace(/^\/+/, '').split('/');
      const restParts = parts.slice(2); // depois de 'api' e 'resource'

      const hasParams = route.path.includes(':');
      const paramRegex = /:([a-zA-Z0-9_]+)/g;
      const paramNames: string[] = [];
      let m: RegExpExecArray | null;
      while ((m = paramRegex.exec(route.path)) != null) {
        paramNames.push(m[1]);
      }

      const pathTemplate =
        '`' +
        route.path.replace(/:([a-zA-Z0-9_]+)/g, '${$1}') +
        '`';

      // Decide operation name
      const opName = getOperationName(route.method, restParts, paramNames);

      if (route.method === 'GET') {
        if (!hasParams) {
          // GET /api/resource -> list
          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}: createFetcherStore<any>(['${route.method}', '${route.path}']),`,
          );
        } else {
          // GET with params -> function returning store
          const paramsSig = paramNames.map((p) => `${p}: string`).join(', ') || 'id: string';

          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}(${paramsSig}) {`,
            `      const path = ${pathTemplate};`,
            `      return createFetcherStore<any>(['${route.method}', path]);`,
            `    },`,
          );
        }
      } else {
        // Mutations: POST, PUT, PATCH, DELETE
        if (!hasParams) {
          // no params -> store direto
          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}: createMutatorStore<any>(async ({ data, revalidate }) => {`,
            `      await fetch('${route.path}', {`,
            `        method: '${route.method}',`,
            `        headers: { 'Content-Type': 'application/json' },`,
            `        body: data ? JSON.stringify(data) : undefined,`,
            `      });`,
            `      revalidate((key) => typeof key === 'string' && key.includes('${route.path}'));`,
            `    }),`,
          );
        } else {
          // com params -> função que cria mutator store
          const paramsSig = paramNames.map((p) => `${p}: string`).join(', ') || 'id: string';

          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}(${paramsSig}) {`,
            `      const path = ${pathTemplate};`,
            `      return createMutatorStore<any>(async ({ data, revalidate }) => {`,
            `        await fetch(path, {`,
            `          method: '${route.method}',`,
            `          headers: { 'Content-Type': 'application/json' },`,
            `          body: data ? JSON.stringify(data) : undefined,`,
            `        });`,
            `        revalidate((key) => typeof key === 'string' && key.includes(path));`,
            `      });`,
            `    },`,
          );
        }
      }
    }

    bodyLines.push('  },');
  }

  bodyLines.push('} as const;');
  bodyLines.push('');
  bodyLines.push('export type ApiClient = typeof api;');

  return `${header}

${bodyLines.join('\n')}
`;
}

// Helper to decide operation name
function getOperationName(
  method: string,
  restParts: string[],
  paramNames: string[],
): string {
  const hasParams = paramNames.length > 0;
  const methodUpper = method.toUpperCase();

  if (methodUpper === 'GET') {
    if (!hasParams && restParts.length === 0) return 'list';
    if (hasParams && restParts.length === 1) {
      const name = paramNames[0] || 'id';
      if (name === 'id') return 'byId';
      return 'by' + name[0].toUpperCase() + name.slice(1);
    }
    // GET /api/resource/something
    const suffix = restParts.join('_').replace(/[^a-zA-Z0-9_]+/g, '');
    return 'get' + (suffix ? '_' + suffix : '');
  }

  if (methodUpper === 'POST') {
    if (!hasParams && restParts.length === 0) return 'create';
    const suffix = restParts.join('_').replace(/[^a-zA-Z0-9_]+/g, '');
    return 'create' + (suffix ? '_' + suffix : '');
  }

  if (methodUpper === 'PUT') {
    if (hasParams) return 'update';
    return 'updateAll';
  }

  if (methodUpper === 'PATCH') {
    if (hasParams) return 'patch';
    return 'patchAll';
  }

  if (methodUpper === 'DELETE') {
    if (hasParams) return 'remove';
    return 'removeAll';
  }

  // fallback
  const suffix = restParts.join('_').replace(/[^a-zA-Z0-9_]+/g, '');
  return method.toLowerCase() + (suffix ? '_' + suffix : '');
}

function generateAll(projectRoot: string, opts: ResolvedBunaConfig) {
  const clientContent = createClientFileContent(opts.routesDir)
  writeFileSafe(projectRoot, opts.outputClient, clientContent)

  const honoContent = createHonoFileContent(opts.routesDir)
  writeFileSafe(projectRoot, opts.outputHono, honoContent)

  const queryContent = createQueryFileContent(projectRoot, opts);
  writeFileSafe(projectRoot, opts.outputQuery, queryContent);

  const typesContent = createRoutesTypesFileContent(projectRoot, opts.routesDir);
  writeFileSafe(projectRoot, opts.outputTypes, typesContent);
}

export function buna(options: BunaConfig = {}): Plugin {
  let root = process.cwd()
  let viteConfig: ResolvedConfig;
  let resolved: ResolvedBunaConfig;

  return {
    name: 'buna',
    enforce: 'pre',

    configResolved(config) {
      viteConfig = config;
      resolved = resolveOptions(options);

      // Geração inicial
      generateAll(config.root, resolved);
    },

    buildStart() {
      if (viteConfig) {
        generateAll(viteConfig.root, resolved);
      }
    },

    configureServer(server) {
      const projectRoot = viteConfig.root;

      // Devtools scaffold endpoint
      server.middlewares.use(
        '/__buna/devtools/scaffold-route',
        (req, res, next) => {
          if (req.method !== 'POST') {
            return next();
          }

          const chunks: Buffer[] = [];

          req.on('data', (chunk) => {
            chunks.push(chunk);
          });

          req.on('end', () => {
            try {
              const raw = Buffer.concat(chunks).toString('utf-8');
              const payload = raw ? JSON.parse(raw) : {};

              // Example: "src/routes/new-route.tsx"
              const relativePath: string =
                payload.path || path.join(resolved.routesDir, 'new-route.tsx');

              const componentName: string = payload.name || 'NewRoutePage';

              const absPath = path.resolve(projectRoot, relativePath);
              const routesDirAbs = path.resolve(projectRoot, resolved.routesDir);

              // Security: ensure route is inside routesDir
              if (!absPath.startsWith(routesDirAbs)) {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(
                  JSON.stringify({
                    ok: false,
                    error: 'Route path must be inside routesDir',
                  }),
                );
                return;
              }

              // Derive routePath from relativePath (e.g. "src/routes/posts.tsx" -> "/posts")
              const routeRelativeToRoutesDir = path
                .relative(resolved.routesDir, relativePath)
                .replace(/\\/g, '/'); // normalize Windows paths

              let routeSubPath = routeRelativeToRoutesDir.replace(/\.tsx?$/, '');
              let routePath = '/' + routeSubPath;

              // Normalize index files to "/" or "/foo"
              if (routePath === '/index' || routePath === '//') {
                routePath = '/';
              }
              routePath = routePath.replace(/\/index$/, '');
              routePath = routePath.replace(/\/+/g, '/');

              if (!routePath) {
                routePath = '/';
              }

              // Ensure directory exists
              const dir = path.dirname(absPath);
              if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
              }

              // Only write if file does not exist
              if (!fs.existsSync(absPath)) {
                const content = scaffoldContent({
                  componentName,
                  relativePath,
                  routePath,
                });

                fs.writeFileSync(absPath, content, 'utf-8');
              }

              // Regenerate .buna files so the new route is registered
              generateAll(projectRoot, resolved);

              res.statusCode = 200;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: true,
                  path: relativePath,
                }),
              );
            } catch (err: any) {
              console.error('[buna devtools scaffold] error:', err);
              res.statusCode = 500;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: false,
                  error: String(err?.message ?? err),
                }),
              );
            }
          });
        },
      );

      // Devtools "open in editor" endpoint
      server.middlewares.use(
        '/__buna/devtools/open-route',
        (req, res, next) => {
          if (req.method !== 'POST') {
            return next();
          }

          const chunks: Buffer[] = [];

          req.on('data', (chunk) => {
            chunks.push(chunk);
          });

          req.on('end', () => {
            try {
              const raw = Buffer.concat(chunks).toString('utf-8');
              const payload = raw ? JSON.parse(raw) : {};

              // Aqui "path" é o path de ROTA, ex: "/settings", "/posts/:id", "/"
              const routePath: string | undefined = payload.path;
              if (!routePath || typeof routePath !== 'string') {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(
                  JSON.stringify({
                    ok: false,
                    error: 'Missing "path" (routePath) in payload',
                  }),
                );
                return;
              }

              // Normalize route to files`s subpath
              // "/", ""          -> "index"
              // "/settings"      -> "settings"
              // "/posts/:id"     -> "posts/[id]"
              // "/blog/"         -> "blog"
              let routeSubPath = routePath.replace(/^\/+/, ''); // tira "/" inicial

              if (!routeSubPath) {
                routeSubPath = 'index';
              }

              if (routeSubPath.endsWith('/')) {
                routeSubPath = routeSubPath.slice(0, -1) || 'index';
              }

              // segmentos dinâmicos :id -> [id]
              routeSubPath = routeSubPath.replace(
                /:([A-Za-z0-9_]+)/g,
                '[$1]',
              );

              // monta caminho relativo dentro de routesDir
              const relativePath = path.join(
                resolved.routesDir,
                `${routeSubPath}.tsx`,
              );

              const absPath = path.resolve(projectRoot, relativePath);
              const routesDirAbs = path.resolve(projectRoot, resolved.routesDir);

              console.log('[open-route] routePath:', routePath);
              console.log('[open-route] routeSubPath:', routeSubPath);
              console.log('[open-route] relativePath:', relativePath);
              console.log('[open-route] absPath:', absPath);
              console.log('[open-route] routesDirAbs:', routesDirAbs);

              // Security: apenas arquivos dentro de routesDir
              if (!absPath.startsWith(routesDirAbs)) {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(
                  JSON.stringify({
                    ok: false,
                    error: 'Route path must be inside routesDir',
                  }),
                );
                return;
              }

              const target = `/__open-in-editor?file=${encodeURIComponent(absPath)}`;

              res.statusCode = 302;
              res.setHeader('Location', target);
              res.end();
            } catch (err: any) {
              console.error('[buna devtools open-route] error:', err);
              res.statusCode = 500;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: false,
                  error: String(err?.message ?? err),
                }),
              );
            }
          });
        },
      );

      const routesDirAbs = path.resolve(projectRoot, resolved.routesDir);
      const serverDirAbs = path.resolve(projectRoot, resolved.serverDir);

      // Ensure watcher tracks these directories
      server.watcher.add([routesDirAbs, serverDirAbs]);

      const onFileChange = (file: string) => {
        const abs = path.resolve(file);

        const inRoutes = abs.startsWith(routesDirAbs);
        const inServer = abs.startsWith(serverDirAbs);

        if (!inRoutes && !inServer) return;

        // Optional: ignore non-code files
        const ext = path.extname(abs);
        if (!['.ts', '.tsx', '.js', '.jsx'].includes(ext)) return;

        // Regenerate .buna files whenever something in routes/ or server/ changes
        generateAll(projectRoot, resolved);
      };

      server.watcher.on('add', onFileChange);
      server.watcher.on('change', onFileChange);
      server.watcher.on('unlink', onFileChange);
    }
  }
}



// HELPERS

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type ApiRouteMeta = {
  method: HttpMethod;
  path: string; // e.g. "/api/posts/:id"
};


export function readApiRoutes(
  projectRoot: string,
  apiFile: string,
  apiBasePath: string,
): ApiRouteMeta[] {
  const fullPath = path.resolve(projectRoot, apiFile);

  if (!fs.existsSync(fullPath)) {
    return [];
  }

  const code = fs.readFileSync(fullPath, 'utf-8');

  const routes: ApiRouteMeta[] = [];

  // qualquer IDENT.get('/path'), api.get('/demo'), router.post('/login'), etc
  const regex =
    /\b([A-Za-z_$][\w$]*)\s*\.(get|post|put|patch|delete)\(\s*['"`]([^'"`]+)['"`]/gi;

  let match: RegExpExecArray | null;

  // normaliza base: '/api/' ou '/' etc
  const base =
    apiBasePath === '/'
      ? ''
      : apiBasePath.endsWith('/')
        ? apiBasePath.slice(0, -1)
        : apiBasePath;

  while ((match = regex.exec(code)) != null) {
    const method = match[2].toUpperCase() as HttpMethod;
    const routePath = match[3]; // '/demo', '/posts/:id', etc.

    // garante que o path comece com '/'
    const cleanRoute =
      routePath.startsWith('/') ? routePath : '/' + routePath;

    // aplica o prefixo da API: '/api' + '/demo' => '/api/demo'
    const fullRoute =
      base + cleanRoute; // se base = '' => fica só '/demo'

    routes.push({ method, path: fullRoute });
  }

  return routes;
}

/**
 * Very simple name generator for a route.
 * Example:
 *   method: GET, path: /api/posts/:id/comments
 *   => "get_api_posts_by_id_comments"
 */
export function routeToName({ method, path }: ApiRouteMeta): string {
  const parts = path
    .replace(/^\/+/, '') // remove leading slash
    .split('/')
    .map((part) => {
      if (part.startsWith(':')) {
        return 'by_' + part.slice(1);
      }
      if (!part) return '';
      return part.replace(/[^a-zA-Z0-9]+/g, '_');
    })
    .filter(Boolean);

  return [method.toLowerCase(), ...parts].join('_');
}


export const scaffoldContent = (props: { routePath: string, componentName: string, relativePath: string }) => `import { CreateComponent } from '@buna/router';
import { useState } from 'hono/jsx';

const ${props.componentName} = CreateComponent('${props.routePath}', ({ params, search, hash }) => {
  const [showDebug, setShowDebug] = useState(false);

  return (
    <div className="h-full  bg-[#0d0d0d] text-slate-100 flex items-center justify-center px-6">
      <section className="w-full max-w-xl rounded-2xl border border-slate-800 bg-slate-900/80 shadow-xl shadow-black/40 p-6 space-y-4">
        <header className="space-y-1">
          <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-emerald-300/80">
            Buna() Route
          </p>
          <h1 className="text-xl font-semibold text-slate-50">
            ${props.componentName}
          </h1>
          <p className="text-[12px] text-slate-400">
            This page was scaffolded by Buna Devtools. Start editing it at
            {' '}
            <code className="font-mono text-[11px] text-slate-300">${props.relativePath}</code>.
          </p>
        </header>

       

        <button
          type="button"
          className="inline-flex items-center justify-center rounded-md border border-emerald-500/60 bg-emerald-500/10 px-3 py-1.5 text-[11px] font-semibold text-emerald-100 hover:bg-emerald-500/20 transition-colors"
          onClick={() => setShowDebug((v) => !v)}
        >
          {showDebug ? 'Hide debug' : 'Show debug'}
        </button>

        {showDebug && (
          <pre className="mt-2 max-h-40 overflow-auto rounded-md bg-slate-950/70 p-3 text-[11px] text-slate-200">
            {JSON.stringify({ params, search, hash }, null, 2)}
          </pre>
        )}
      </section>
    </div>
  );
});

${props.componentName}.meta = ({ params }) => {
  return {
    title: '${props.componentName} – Buna Playground',
    description: 'Scaffolded page created by Buna Devtools.',
    keywords: ['buna', 'devtools', '${props.componentName}', 'route'],
  };
};

export default ${props.componentName};
`;