import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ResolvedConfig } from 'vite'
import type { BunaConfig, ResolvedBunaConfig, } from "@buna/config"
import type { BunaRuntime } from '@buna/config'

const DEFAULT_ROUTES_DIR = 'src/routes'
const DEFAULT_SERVER_DIR = 'src/server'
const DEFAULT_OUTPUT_CLIENT = '.buna/client-routes.generated.ts'
const DEFAULT_OUTPUT_SERVER = '.buna/server-routes.generated.ts'
const DEFAULT_API_PATH = '/api'
const DEFAULT_API_FILE = 'src/server/api.ts'
const DEFAULT_OUTPUT_QUERY = '.buna/query.generated.ts'
const DEFAULT_OUTPUT_TYPES = '.buna/routes.generated.d.ts'


function filePathToPath(filePath: string): string {
  return filePath
    .replace(/\.tsx?$/g, '')
    .replace(/\.mdx?$/g, '')
    .replace(/^\/?index$/, '/')
    .replace(/\/index$/, '')
    .replace(/\[\.{3}.+\]/, '*')
    .replace(/\((.+?)\)/g, '')
    .replace(/\[(.+?)\]/g, ':$1')
    .replace(/\/\/+/g, '/')
    .replace(/^\/*/, '/'); // garante que começa com '/'
}


function resolveOptions(opts: BunaConfig = {}): ResolvedBunaConfig {
  return {
    routesDir: opts.routesDir ?? DEFAULT_ROUTES_DIR,
    serverDir: opts.serverDir ?? DEFAULT_SERVER_DIR,
    outputClient: opts.outputClient ?? DEFAULT_OUTPUT_CLIENT,
    outputHono: opts.outputHono ?? DEFAULT_OUTPUT_SERVER,
    apiFile: opts.apiFile ?? DEFAULT_API_FILE, // or src/server/api.ts in template final
    outputQuery: opts.outputQuery ?? DEFAULT_OUTPUT_QUERY,
    apiBasePath: opts.apiBasePath ?? DEFAULT_API_PATH,
    outputTypes: opts.outputTypes ?? DEFAULT_OUTPUT_TYPES,
    vite: opts.vite ?? {},
    // runtime: opts.runtime as BunaRuntime
  };
}

function resolveModuleFile(apiDir: string, importSource: string): string | null {
  // Base path built from the imported path (may not contain extension)
  const basePath = path.resolve(apiDir, importSource);

  // Candidates: handle .ts, .tsx, .js, .mjs, .cjs and direct file
  const candidates = [
    basePath,
    basePath + '.ts',
    basePath + '.tsx',
    basePath + '.js',
    basePath + '.mjs',
    basePath + '.cjs',
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  // If nothing was found, return null so caller can decide what to do
  return null;
}

// Helper to write files
function writeFileSafe(projectRoot: string, relPath: string, content: string) {
  const fullPath = path.resolve(projectRoot, relPath)
  const dir = path.dirname(fullPath)

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(fullPath, content, 'utf8')
}

function createGlobBase(routesDir: string): string {
  let dir = routesDir.replace(/\\/g, '/')
  dir = dir.replace(/^\.?\//, '') // remove leading "./"
  return '/' + dir.replace(/\/$/, '')
}

function createRoutesTypesFileContent(projectRoot: string, routesDir: string): string {
  const routes: { path: string; params: string[] }[] = [];

  const absRoutesDir = path.join(projectRoot, routesDir);

  if (!fs.existsSync(absRoutesDir)) {
    return `// AUTO-GENERATED BY buna-plugin. NO ROUTES DIRECTORY FOUND.
export {};
`;
  }

  const entries: string[] = [];

  const walk = (dir: string) => {
    const dirents = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of dirents) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        continue;
      }

      const ext = path.extname(entry.name);
      if (!['.tsx', '.jsx', '.mdx'].includes(ext)) continue;

      entries.push(full);
    }
  };

  walk(absRoutesDir);

  for (const absFile of entries) {
    const relFromRoutes = path.relative(absRoutesDir, absFile).replace(/\\/g, '/');
    const routePath = filePathToPath(relFromRoutes);

    // opcional: ignorar rotas especiais que não são "pages"
    // ex: _error, _not-found, _layout etc.
    const lastSegment = routePath.split('/').pop() || '';
    if (lastSegment.startsWith('_')) {
      continue;
    }

    const paramNames: string[] = [];
    const paramRegex = /:([a-zA-Z0-9_]+)/g;
    let m: RegExpExecArray | null;
    while ((m = paramRegex.exec(routePath)) != null) {
      paramNames.push(m[1]);
    }

    routes.push({ path: routePath, params: paramNames });
  }

  if (routes.length === 0) {
    return `// AUTO-GENERATED BY buna-plugin. NO ROUTES FOUND.
export {};
`;
  }

  // Ordena para ter determinismo
  routes.sort((a, b) => a.path.localeCompare(b.path));

  const pathUnion = routes.map((r) => `'${r.path}'`).join(' | ');

  const paramsLines = routes
    .map((r) => {
      if (r.params.length === 0) {
        return `    '${r.path}': {};`;
      }
      const fields = r.params.map((p) => `${p}: string;`).join(' ');
      return `    '${r.path}': { ${fields} };`;
    })
    .join('\n');

  const searchLines = routes
    .map((r) => `    '${r.path}': Record<string, string>;`)
    .join('\n');

  return `// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import type { RouteProps, RouteComponent } from '@buna/router';
import type { HtmlEscapedString } from 'hono/utils/html';

declare module '@buna/router' {
  export type FileRoutePath =
    ${pathUnion};

  export interface FileRouteParamsMap {
${paramsLines}
  }

  export interface FileRouteSearchMap {
${searchLines}
  }

  export type FileRouteProps<P extends FileRoutePath, TExtraProps = unknown> =
    RouteProps<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>;

  export type FileRouteComponent<P extends FileRoutePath, TExtraProps = unknown> =
    RouteComponent<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>;

  export function CreateComponent<P extends FileRoutePath, TExtraProps = unknown>(
    path: P,
    render: (
      props: RouteProps<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>
    ) => HtmlEscapedString | Promise<HtmlEscapedString>,
    options?: RouteComponent<FileRouteParamsMap[P], FileRouteSearchMap[P]>
  ): RouteComponent<FileRouteParamsMap[P], FileRouteSearchMap[P], TExtraProps>;
}
`;
}

/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createClientFileContent(routesDir: string): string {
  const base = createGlobBase(routesDir)
  const globPattern = `${base}/**/*.{tsx,jsx,mdx}`

  return `/// <reference types="vite/client" />
  // AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
  import { RouteModule } from '@buna/router/router-core'
import { createRouterConfigFromGlob } from '@buna/router/runtime-client'

const files = import.meta.glob('${globPattern}', { eager: true })  as Record<string, RouteModule>

export const config = createRouterConfigFromGlob(files, { routesBase: '${base}' })

export const routes = config.routes
export const routeComponents = config.routeComponents
export const routesMeta = config.routesMeta
export const directoryLayers = config.directoryLayers
export const directoryOrder = config.directoryOrder
export const $router = config.$router
export type RoutingKeys = keyof typeof routeComponents
`
}

/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createHonoFileContent(routesDir: string): string {
  const base = createGlobBase(routesDir)
  const globPattern = `${base}/**/*.{tsx,jsx,mdx}`

  return `/// <reference types="vite/client" />
// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import { createHonoAppFromGlob } from '@buna/router/runtime-hono'

const files = import.meta.glob('${globPattern}', { eager: true })

const config = createHonoAppFromGlob(files, { routesBase: '${base}' })

export const honoRoutesMeta = config.routesMeta
export const honoDirectoryLayers = config.directoryLayers
export const honoDirectoryOrder = config.directoryOrder
export default config.app
`
}


/**
 * Function that generates a string to be used to generate a file with it's content.
 * @param routesDir Routes directory
 * @returns A string to generate the file
 */
function createQueryFileContent(projectRoot: string, opts: ResolvedBunaConfig): string {
  const apiRoutes = readApiRoutes(projectRoot, opts.apiFile, opts.apiBasePath);

  if (apiRoutes.length === 0) {
    return `// AUTO-GENERATED BY buna-plugin. NO API ROUTES FOUND.
export const api = {} as const;
export type ApiClient = typeof api;
`;
  }


  const header = `// AUTO-GENERATED BY buna-plugin. DO NOT EDIT.
import { createFetcherStore, createMutatorStore } from '@buna/router/query';
`;

  // Group routes by first segment after /api
  const groups: Record<string, ApiRouteMeta[]> = {};

  for (const route of apiRoutes) {
    const parts = route.path.replace(/^\/+/, '').split('/'); // ['api', 'posts', ':id']
    const resource = parts[1] || 'root';

    if (!groups[resource]) groups[resource] = [];
    groups[resource].push(route);
  }

  const bodyLines: string[] = [];
  bodyLines.push('export const api = {');

  for (const [resource, routes] of Object.entries(groups)) {
    bodyLines.push(`  ${resource}: {`);

    for (const route of routes) {
      const parts = route.path.replace(/^\/+/, '').split('/');
      const restParts = parts.slice(2); // depois de 'api' e 'resource'

      const hasParams = route.path.includes(':');
      const paramRegex = /:([a-zA-Z0-9_]+)/g;
      const paramNames: string[] = [];
      let m: RegExpExecArray | null;
      while ((m = paramRegex.exec(route.path)) != null) {
        paramNames.push(m[1]);
      }

      const pathTemplate =
        '`' +
        route.path.replace(/:([a-zA-Z0-9_]+)/g, '${$1}') +
        '`';

      // Decide operation name
      const opName = getOperationName(route.method, restParts, paramNames);

      if (route.method === 'GET') {
        if (!hasParams) {
          // GET /api/resource -> list
          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}: createFetcherStore<any>(['${route.method}', '${route.path}']),`,
          );
        } else {
          // GET with params -> function returning store
          const paramsSig = paramNames.map((p) => `${p}: string`).join(', ') || 'id: string';

          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}(${paramsSig}) {`,
            `      const path = ${pathTemplate};`,
            `      return createFetcherStore<any>(['${route.method}', path]);`,
            `    },`,
          );
        }
      } else {
        // Mutations: POST, PUT, PATCH, DELETE
        if (!hasParams) {
          // no params -> store direto
          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}: createMutatorStore<any>(async ({ data, revalidate }) => {`,
            `      await fetch('${route.path}', {`,
            `        method: '${route.method}',`,
            `        headers: { 'Content-Type': 'application/json' },`,
            `        body: data ? JSON.stringify(data) : undefined,`,
            `      });`,
            `      revalidate((key) => typeof key === 'string' && key.includes('${route.path}'));`,
            `    }),`,
          );
        } else {
          // com params -> função que cria mutator store
          const paramsSig = paramNames.map((p) => `${p}: string`).join(', ') || 'id: string';

          bodyLines.push(
            `    // ${route.method} ${route.path}`,
            `    ${opName}(${paramsSig}) {`,
            `      const path = ${pathTemplate};`,
            `      return createMutatorStore<any>(async ({ data, revalidate }) => {`,
            `        await fetch(path, {`,
            `          method: '${route.method}',`,
            `          headers: { 'Content-Type': 'application/json' },`,
            `          body: data ? JSON.stringify(data) : undefined,`,
            `        });`,
            `        revalidate((key) => typeof key === 'string' && key.includes(path));`,
            `      });`,
            `    },`,
          );
        }
      }
    }

    bodyLines.push('  },');
  }

  bodyLines.push('} as const;');
  bodyLines.push('');
  bodyLines.push('export type ApiClient = typeof api;');

  return `${header}

${bodyLines.join('\n')}
`;
}

// PATCH API FILE
function patchApiFile(options: {
  projectRoot: string;
  apiFileRelative: string;
  resourceSlug: string;
}) {
  const { projectRoot, apiFileRelative, resourceSlug } = options;
  const absApiFile = path.resolve(projectRoot, apiFileRelative);

  if (!fs.existsSync(absApiFile)) {
    console.warn('[buna devtools] apiFile not found:', absApiFile);
    return;
  }

  const importId = `${resourceSlug}Module`;
  const importPath = `./modules/${resourceSlug}.module`;
  const routeLine = `api.route('/${resourceSlug}', ${importId});`;

  let content = fs.readFileSync(absApiFile, 'utf-8');

  // já tem import?
  if (!content.includes(importPath)) {
    const importLine = `import ${importId} from '${importPath}';\n`;

    const apiIndex = content.indexOf('const api');
    if (apiIndex !== -1) {
      content = content.slice(0, apiIndex) + importLine + content.slice(apiIndex);
    } else {
      content = importLine + content;
    }
  }

  // já tem api.route?
  if (!content.includes(routeLine)) {
    const exportIndex = content.lastIndexOf('export default api');
    if (exportIndex !== -1) {
      content =
        content.slice(0, exportIndex) +
        routeLine +
        '\n\n' +
        content.slice(exportIndex);
    } else {
      // fallback: só adiciona no final
      content += `\n${routeLine}\n`;
    }
  }

  fs.writeFileSync(absApiFile, content, 'utf-8');
}

function normalizeResourceSlug(
  routePath: string,
  explicitName?: string,
): string {
  if (explicitName && explicitName.trim()) {
    return explicitName.trim().toLowerCase();
  }

  // Eg: "/posts/:id/comments" => ["posts", ":id", "comments"]
  const segments = routePath
    .split('/')
    .map((s) => s.trim())
    .filter(Boolean);

  // get last segment that is not a param
  let lastStatic =
    [...segments].reverse().find((s) => !s.startsWith(':')) ?? 'resource';

  lastStatic = lastStatic.replace(/[^a-zA-Z0-9-_]/g, '').toLowerCase();

  if (!lastStatic) {
    return 'resource';
  }

  return lastStatic;
}

function toPascalCase(input: string): string {
  return input
    .split(/[-_]/g)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function singularize(slug: string): string {
  if (slug.endsWith('ies')) return slug.slice(0, -3) + 'y';
  if (slug.endsWith('s')) return slug.slice(0, -1);
  return slug;
}

// Helper to decide operation name
function getOperationName(
  method: string,
  restParts: string[],
  paramNames: string[],
): string {
  const hasParams = paramNames.length > 0;
  const methodUpper = method.toUpperCase();

  if (methodUpper === 'GET') {
    if (!hasParams && restParts.length === 0) return 'list';
    if (hasParams && restParts.length === 1) {
      const name = paramNames[0] || 'id';
      if (name === 'id') return 'byId';
      return 'by' + name[0].toUpperCase() + name.slice(1);
    }
    // GET /api/resource/something
    const suffix = restParts.join('_').replace(/[^a-zA-Z0-9_]+/g, '');
    return 'get' + (suffix ? '_' + suffix : '');
  }

  if (methodUpper === 'POST') {
    if (!hasParams && restParts.length === 0) return 'create';
    const suffix = restParts.join('_').replace(/[^a-zA-Z0-9_]+/g, '');
    return 'create' + (suffix ? '_' + suffix : '');
  }

  if (methodUpper === 'PUT') {
    if (hasParams) return 'update';
    return 'updateAll';
  }

  if (methodUpper === 'PATCH') {
    if (hasParams) return 'patch';
    return 'patchAll';
  }

  if (methodUpper === 'DELETE') {
    if (hasParams) return 'remove';
    return 'removeAll';
  }

  // fallback
  const suffix = restParts.join('_').replace(/[^a-zA-Z0-9_]+/g, '');
  return method.toLowerCase() + (suffix ? '_' + suffix : '');
}

function generateAll(projectRoot: string, opts: ResolvedBunaConfig) {
  const clientContent = createClientFileContent(opts.routesDir)
  writeFileSafe(projectRoot, opts.outputClient, clientContent)

  const honoContent = createHonoFileContent(opts.routesDir)
  writeFileSafe(projectRoot, opts.outputHono, honoContent)

  const queryContent = createQueryFileContent(projectRoot, opts);
  writeFileSafe(projectRoot, opts.outputQuery, queryContent);

  const typesContent = createRoutesTypesFileContent(projectRoot, opts.routesDir);
  writeFileSafe(projectRoot, opts.outputTypes, typesContent);
}

export function buna(options: BunaConfig = {}): Plugin {
  let root = process.cwd()
  let viteConfig: ResolvedConfig;
  let resolved: ResolvedBunaConfig;

  return {
    name: 'buna',
    enforce: 'pre',

    configResolved(config) {
      viteConfig = config;
      resolved = resolveOptions(options);

      // Geração inicial
      generateAll(config.root, resolved);
    },

    buildStart() {
      if (viteConfig) {
        generateAll(viteConfig.root, resolved);
      }
    },

    configureServer(server) {
      const projectRoot = viteConfig.root;

      // Devtools scaffold endpoint
      server.middlewares.use(
        '/__buna/devtools/scaffold-route',
        (req, res, next) => {
          if (req.method !== 'POST') {
            return next();
          }

          const chunks: Buffer[] = [];

          req.on('data', (chunk) => {
            chunks.push(chunk);
          });

          req.on('end', () => {
            try {
              const raw = Buffer.concat(chunks).toString('utf-8');
              const payload = raw ? JSON.parse(raw) : {};

              // Example: "src/routes/new-route.tsx"
              const relativePath: string =
                payload.path || path.join(resolved.routesDir, 'new-route.tsx');

              const componentName: string = payload.name || 'NewRoutePage';

              const absPath = path.resolve(projectRoot, relativePath);
              const routesDirAbs = path.resolve(projectRoot, resolved.routesDir);

              // Security: ensure route is inside routesDir
              if (!absPath.startsWith(routesDirAbs)) {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(
                  JSON.stringify({
                    ok: false,
                    error: 'Route path must be inside routesDir',
                  }),
                );
                return;
              }

              // Derive routePath from relativePath (e.g. "src/routes/posts.tsx" -> "/posts")
              const routeRelativeToRoutesDir = path
                .relative(resolved.routesDir, relativePath)
                .replace(/\\/g, '/'); // normalize Windows paths

              let routeSubPath = routeRelativeToRoutesDir.replace(/\.tsx?$/, '');
              let routePath = '/' + routeSubPath;

              // Normalize index files to "/" or "/foo"
              if (routePath === '/index' || routePath === '//') {
                routePath = '/';
              }
              routePath = routePath.replace(/\/index$/, '');
              routePath = routePath.replace(/\/+/g, '/');

              if (!routePath) {
                routePath = '/';
              }

              // Ensure directory exists
              const dir = path.dirname(absPath);
              if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
              }

              // Only write if file does not exist
              if (!fs.existsSync(absPath)) {
                const content = scaffoldContent({
                  componentName,
                  relativePath,
                  routePath,
                });

                fs.writeFileSync(absPath, content, 'utf-8');
              }

              // Regenerate .buna files so the new route is registered
              generateAll(projectRoot, resolved);

              res.statusCode = 200;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: true,
                  path: relativePath,
                }),
              );
            } catch (err: any) {
              console.error('[buna devtools scaffold] error:', err);
              res.statusCode = 500;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: false,
                  error: String(err?.message ?? err),
                }),
              );
            }
          });
        },
      );

      // Devtools "open in editor" endpoint
      server.middlewares.use(
        '/__buna/devtools/open-route',
        (req, res, next) => {
          if (req.method !== 'POST') {
            return next();
          }

          const chunks: Buffer[] = [];

          req.on('data', (chunk) => {
            chunks.push(chunk);
          });

          req.on('end', () => {
            try {
              const raw = Buffer.concat(chunks).toString('utf-8');
              const payload = raw ? JSON.parse(raw) : {};

              // Aqui "path" é o path de ROTA, ex: "/settings", "/posts/:id", "/"
              const routePath: string | undefined = payload.path;
              if (!routePath || typeof routePath !== 'string') {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(
                  JSON.stringify({
                    ok: false,
                    error: 'Missing "path" (routePath) in payload',
                  }),
                );
                return;
              }

              // Normalize route to files`s subpath
              // "/", ""          -> "index"
              // "/settings"      -> "settings"
              // "/posts/:id"     -> "posts/[id]"
              // "/blog/"         -> "blog"
              let routeSubPath = routePath.replace(/^\/+/, ''); // tira "/" inicial

              if (!routeSubPath) {
                routeSubPath = 'index';
              }

              if (routeSubPath.endsWith('/')) {
                routeSubPath = routeSubPath.slice(0, -1) || 'index';
              }

              // segmentos dinâmicos :id -> [id]
              routeSubPath = routeSubPath.replace(
                /:([A-Za-z0-9_]+)/g,
                '[$1]',
              );

              // monta caminho relativo dentro de routesDir
              const relativePath = path.join(
                resolved.routesDir,
                `${routeSubPath}.tsx`,
              );

              const absPath = path.resolve(projectRoot, relativePath);
              const routesDirAbs = path.resolve(projectRoot, resolved.routesDir);

              console.log('[open-route] routePath:', routePath);
              console.log('[open-route] routeSubPath:', routeSubPath);
              console.log('[open-route] relativePath:', relativePath);
              console.log('[open-route] absPath:', absPath);
              console.log('[open-route] routesDirAbs:', routesDirAbs);

              // Security: apenas arquivos dentro de routesDir
              if (!absPath.startsWith(routesDirAbs)) {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(
                  JSON.stringify({
                    ok: false,
                    error: 'Route path must be inside routesDir',
                  }),
                );
                return;
              }

              const target = `/__open-in-editor?file=${encodeURIComponent(absPath)}`;

              res.statusCode = 302;
              res.setHeader('Location', target);
              res.end();
            } catch (err: any) {
              console.error('[buna devtools open-route] error:', err);
              res.statusCode = 500;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: false,
                  error: String(err?.message ?? err),
                }),
              );
            }
          });
        },
      );

      server.middlewares.use(
        '/__buna/devtools/scaffold-crud',
        (req, res, next) => {
          if (req.method !== 'POST') {
            return next();
          }

          const chunks: Buffer[] = [];

          req.on('data', (chunk) => {
            chunks.push(chunk);
          });

          req.on('end', () => {
            try {
              const raw = Buffer.concat(chunks).toString('utf-8');
              const payload = raw ? JSON.parse(raw) : {};

              // Ex: "/users", "/posts/:id"
              const routePath: string = payload.routePath || '/resource';
              const explicitName: string | undefined = payload.resourceName;

              const resourceSlug = normalizeResourceSlug(routePath, explicitName);
              const pascalName = toPascalCase(singularize(resourceSlug));

              const projectRoot = viteConfig.root;
              const serverDirAbs = path.resolve(projectRoot, resolved.serverDir);
              const servicesDir = path.join(serverDirAbs, 'services');
              const modulesDir = path.join(serverDirAbs, 'modules');

              fs.mkdirSync(servicesDir, { recursive: true });
              fs.mkdirSync(modulesDir, { recursive: true });

              const serviceFile = path.join(
                servicesDir,
                `${resourceSlug}.service.ts`,
              );
              const moduleFile = path.join(
                modulesDir,
                `${resourceSlug}.module.ts`,
              );

              if (!fs.existsSync(serviceFile)) {
                fs.writeFileSync(
                  serviceFile,
                  createServiceTemplate({ pascalName, resourceSlug }),
                  'utf-8',
                );
              }

              if (!fs.existsSync(moduleFile)) {
                fs.writeFileSync(
                  moduleFile,
                  createModuleTemplate({ pascalName, resourceSlug }),
                  'utf-8',
                );
              }

              patchApiFile({
                projectRoot,
                apiFileRelative: resolved.apiFile,
                resourceSlug,
              });

              // Se quiser regenerar .buna também:
              // generateAll(projectRoot, resolved);

              res.statusCode = 200;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: true,
                  serviceFile: path.relative(projectRoot, serviceFile),
                  moduleFile: path.relative(projectRoot, moduleFile),
                }),
              );
            } catch (err: any) {
              console.error('[buna devtools scaffold-crud] error:', err);
              res.statusCode = 500;
              res.setHeader('Content-Type', 'application/json');
              res.end(
                JSON.stringify({
                  ok: false,
                  error: String(err?.message ?? err),
                }),
              );
            }
          });
        },
      );

      const routesDirAbs = path.resolve(projectRoot, resolved.routesDir);
      const serverDirAbs = path.resolve(projectRoot, resolved.serverDir);

      // Ensure watcher tracks these directories
      server.watcher.add([routesDirAbs, serverDirAbs]);

      const onFileChange = (file: string) => {
        const abs = path.resolve(file);

        const inRoutes = abs.startsWith(routesDirAbs);
        const inServer = abs.startsWith(serverDirAbs);

        if (!inRoutes && !inServer) return;

        // Optional: ignore non-code files
        const ext = path.extname(abs);
        if (!['.ts', '.tsx', '.js', '.jsx'].includes(ext)) return;

        // Regenerate .buna files whenever something in routes/ or server/ changes
        generateAll(projectRoot, resolved);
      };

      server.watcher.on('add', onFileChange);
      server.watcher.on('change', onFileChange);
      server.watcher.on('unlink', onFileChange);
    }
  }
}



// HELPERS

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type ApiRouteMeta = {
  method: HttpMethod;
  path: string; // e.g. "/api/posts/:id"
};


// READ API FILE
export function readApiRoutes(
  projectRoot: string,
  apiFile: string,
  apiBasePath: string,
): ApiRouteMeta[] {
  const fullPath = path.resolve(projectRoot, apiFile);

  if (!fs.existsSync(fullPath)) {
    return [];
  }

  const code = fs.readFileSync(fullPath, 'utf-8');

  const routes: ApiRouteMeta[] = [];

  // Normalize API base path: '/', '/api', '/api/'
  const base =
    apiBasePath === '/'
      ? ''
      : apiBasePath.endsWith('/')
        ? apiBasePath.slice(0, -1)
        : apiBasePath;

  // 1) Direct routes declared in api.ts using .get/.post/.put/.patch/.delete
  const directRegex =
    /\b([A-Za-z_$][\w$]*)\s*\.(get|post|put|patch|delete)\(\s*['"`]([^'"`]+)['"`]/gi;

  let match: RegExpExecArray | null;

  while ((match = directRegex.exec(code)) != null) {
    const method = match[2].toUpperCase() as HttpMethod;
    const routePath = match[3]; // e.g. '/demo', '/posts/:id'

    // Ensure route starts with '/'
    const cleanRoute =
      routePath.startsWith('/') ? routePath : '/' + routePath;

    // Apply API base prefix: '/api' + '/demo' => '/api/demo'
    const fullRoute = base + cleanRoute;

    routes.push({ method, path: fullRoute });
  }

  // 2) Collect default imports from relative modules
  //    Example: import usersModule from './modules/users.module';
  const importRegex =
    /import\s+([A-Za-z_$][\w$]*)\s+from\s+['"`]([^'"`]+)['"`]\s*;?/g;

  const apiDir = path.dirname(fullPath);
  const moduleImportMap = new Map<string, string>(); // identifier -> absolute file path

  while ((match = importRegex.exec(code)) != null) {
    const importName = match[1];   // e.g. usersModule
    const importSource = match[2]; // e.g. './modules/users.module'

    // Ignore library imports, only care about relative paths
    if (!importSource.startsWith('.')) {
      continue;
    }

    // Try to resolve the real module file on disk (handles missing extensions)
    const absModulePath = resolveModuleFile(apiDir, importSource);

    if (!absModulePath) {
      // Optional: log once if a module cannot be resolved
      // console.warn('[buna-plugin] Could not resolve module for import:', importSource);
      continue;
    }

    moduleImportMap.set(importName, absModulePath);
  }

  // 3) Find api.route('/base', moduleIdentifier) calls
  //    Example: api.route('/users', usersModule);
  const routeRegex =
    /\b([A-Za-z_$][\w$]*)\s*\.route\(\s*['"`]([^'"`]+)['"`]\s*,\s*([A-Za-z_$][\w$]*)\s*\)/g;

  while ((match = routeRegex.exec(code)) != null) {
    // const apiIdent = match[1]; // usually "api", but we don't need it here
    const routeBasePath = match[2];  // e.g. '/users'
    const moduleIdent = match[3];    // e.g. 'usersModule'

    const moduleFile = moduleImportMap.get(moduleIdent);
    if (!moduleFile) {
      // Module not imported as a default local file, skip it
      continue;
    }

    // Normalize base route (no trailing slash)
    let baseRoute =
      routeBasePath.startsWith('/') ? routeBasePath : '/' + routeBasePath;
    baseRoute = baseRoute.replace(/\/+$/, ''); // remove trailing slashes
    if (baseRoute === '') baseRoute = '/';

    // Read routes inside the module file (GET/POST/PUT/PATCH/DELETE)
    readModuleRoutes(moduleFile, base, baseRoute, routes);
  }

  return routes;
}

function readModuleRoutes(
  moduleFile: string,
  apiBase: string,
  routeBase: string,
  routes: ApiRouteMeta[],
) {
  if (!fs.existsSync(moduleFile)) {
    return;
  }

  const code = fs.readFileSync(moduleFile, 'utf-8');

  // Match any "xxx.get('/path')" or "xxx.post('/path')" style calls
  const regex =
    /\b([A-Za-z_$][\w$]*)\s*\.(get|post|put|patch|delete)\(\s*['"`]([^'"`]+)['"`]/gi;

  let match: RegExpExecArray | null;

  while ((match = regex.exec(code)) != null) {
    const method = match[2].toUpperCase() as HttpMethod;
    const localPath = match[3]; // e.g. '/', '/:id', '/comments/:id'

    // Normalize local path inside the module
    let normalizedLocal =
      localPath.startsWith('/') ? localPath : '/' + localPath;

    // Combine module base route with local path
    // Examples:
    //   routeBase = '/users', normalizedLocal = '/'    => '/users'
    //   routeBase = '/users', normalizedLocal = '/:id' => '/users/:id'
    let combined: string;
    if (normalizedLocal === '/' || normalizedLocal === '') {
      combined = routeBase;
    } else {
      combined = routeBase + normalizedLocal;
    }

    // Normalize duplicate slashes and ensure it starts with '/'
    combined = combined.replace(/\/+/g, '/');
    if (!combined.startsWith('/')) {
      combined = '/' + combined;
    }

    // Apply API base: '/api' + '/users/:id' => '/api/users/:id'
    const fullRoute = apiBase + combined;

    routes.push({ method, path: fullRoute });
  }
}

/**
 * Very simple name generator for a route.
 * Example:
 *   method: GET, path: /api/posts/:id/comments
 *   => "get_api_posts_by_id_comments"
 */
export function routeToName({ method, path }: ApiRouteMeta): string {
  const parts = path
    .replace(/^\/+/, '') // remove leading slash
    .split('/')
    .map((part) => {
      if (part.startsWith(':')) {
        return 'by_' + part.slice(1);
      }
      if (!part) return '';
      return part.replace(/[^a-zA-Z0-9]+/g, '_');
    })
    .filter(Boolean);

  return [method.toLowerCase(), ...parts].join('_');
}


export const scaffoldContent = (props: { routePath: string, componentName: string, relativePath: string }) => `import { CreateComponent } from '@buna/router';
import { useState } from 'hono/jsx';

const ${props.componentName} = CreateComponent('${props.routePath}', ({ params, search, hash }) => {
  const [showDebug, setShowDebug] = useState(false);

  return (
    <div className="h-full  bg-[#0d0d0d] text-slate-100 flex items-center justify-center px-6">
      <section className="w-full max-w-xl rounded-2xl border border-slate-800 bg-slate-900/80 shadow-xl shadow-black/40 p-6 space-y-4">
        <header className="space-y-1">
          <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-emerald-300/80">
            Buna() Route
          </p>
          <h1 className="text-xl font-semibold text-slate-50">
            ${props.componentName}
          </h1>
          <p className="text-[12px] text-slate-400">
            This page was scaffolded by Buna Devtools. Start editing it at
            {' '}
            <code className="font-mono text-[11px] text-slate-300">${props.relativePath}</code>.
          </p>
        </header>

       

        <button
          type="button"
          className="inline-flex items-center justify-center rounded-md border border-emerald-500/60 bg-emerald-500/10 px-3 py-1.5 text-[11px] font-semibold text-emerald-100 hover:bg-emerald-500/20 transition-colors"
          onClick={() => setShowDebug((v) => !v)}
        >
          {showDebug ? 'Hide debug' : 'Show debug'}
        </button>

        {showDebug && (
          <pre className="mt-2 max-h-40 overflow-auto rounded-md bg-slate-950/70 p-3 text-[11px] text-slate-200">
            {JSON.stringify({ params, search, hash }, null, 2)}
          </pre>
        )}
      </section>
    </div>
  );
});

${props.componentName}.meta = ({ params }) => {
  return {
    title: '${props.componentName} – Buna Playground',
    description: 'Scaffolded page created by Buna Devtools.',
    keywords: ['buna', 'devtools', '${props.componentName}', 'route'],
  };
};

export default ${props.componentName};
`;


// SERVICE TEMPLATE
type CrudTemplateContext = {
  pascalName: string;  // "User"
  resourceSlug: string; // "users"
};

function createServiceTemplate(ctx: CrudTemplateContext): string {
  const { pascalName, resourceSlug } = ctx;
  const entityName = pascalName;
  const collectionName = resourceSlug;

  return `// AUTO-GENERATED BY buna-plugin.
// You can freely edit this file.

export type ${entityName} = {
  id: string;
  // TODO: add more fields here
};

let ${collectionName}: ${entityName}[] = [];

export async function list${entityName}s(): Promise<${entityName}[]> {
  return ${collectionName};
}

export async function get${entityName}ById(id: string): Promise<${entityName} | null> {
  return ${collectionName}.find((item) => item.id === id) ?? null;
}

export async function create${entityName}(data: Partial<${entityName}>): Promise<${entityName}> {
  const item: ${entityName} = {
    id: String(Date.now()),
    ...data,
  } as ${entityName};

  ${collectionName}.push(item);
  return item;
}

export async function update${entityName}(id: string, data: Partial<${entityName}>): Promise<${entityName} | null> {
  const index = ${collectionName}.findIndex((item) => item.id === id);
  if (index === -1) return null;

  const updated = { ...${collectionName}[index], ...data } as ${entityName};
  ${collectionName}[index] = updated;
  return updated;
}

export async function delete${entityName}(id: string): Promise<boolean> {
  const before = ${collectionName}.length;
  ${collectionName} = ${collectionName}.filter((item) => item.id !== id);
  return ${collectionName}.length < before;
}
`;
}


// MODULE TEMPLATE
function createModuleTemplate(ctx: CrudTemplateContext): string {
  const { pascalName, resourceSlug } = ctx;
  const entityName = pascalName;
  const serviceImportId = `${resourceSlug}Service`;
  const moduleConst = `${resourceSlug}Module`;

  return `// AUTO-GENERATED BY buna-plugin.
// Basic CRUD Hono module for "${resourceSlug}"

import { Hono } from 'hono';
import * as ${serviceImportId} from '../services/${resourceSlug}.service';

const ${moduleConst} = new Hono();

// GET /${resourceSlug}
${moduleConst}.get('/', async (c) => {
  const items = await ${serviceImportId}.list${entityName}s();
  return c.json({ data: items });
});

// GET /${resourceSlug}/:id
${moduleConst}.get('/:id', async (c) => {
  const id = c.req.param('id');
  const item = await ${serviceImportId}.get${entityName}ById(id);
  if (!item) {
    return c.json({ error: '${entityName} not found' }, 404);
  }
  return c.json({ data: item });
});

// POST /${resourceSlug}
${moduleConst}.post('/', async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const created = await ${serviceImportId}.create${entityName}(body);
  return c.json({ data: created }, 201);
});

// PUT /${resourceSlug}/:id
${moduleConst}.put('/:id', async (c) => {
  const id = c.req.param('id');
  const body = await c.req.json().catch(() => ({}));
  const updated = await ${serviceImportId}.update${entityName}(id, body);
  if (!updated) {
    return c.json({ error: '${entityName} not found' }, 404);
  }
  return c.json({ data: updated });
});

// DELETE /${resourceSlug}/:id
${moduleConst}.delete('/:id', async (c) => {
  const id = c.req.param('id');
  const ok = await ${serviceImportId}.delete${entityName}(id);
  if (!ok) {
    return c.json({ error: '${entityName} not found' }, 404);
  }
  return c.json({ ok: true });
});

export default ${moduleConst};
`;
}