import { join, dirname } from "node:path";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { note } from "@clack/prompts";
import { DEFAULTS } from "../constants";
import type { ScaffoldOptions } from "../types";
import logoSvg from "../public/logo-svg"

export async function scaffoldBaseTemplate(opts: ScaffoldOptions) {
  const files = buildBaseTemplateFiles(opts);

  for (const [relPath, content] of Object.entries(files)) {
    const target = join(opts.dir, relPath);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
  }

  // clean possible existing .buna from previous attempts
  await rm(join(opts.dir, ".buna"), {
    recursive: true,
    force: true,
  }).catch(() => { });

  note(`Project created at ${opts.dir}`, "Files written");
}

function buildBaseTemplateFiles(opts: ScaffoldOptions): Record<string, string> {
  const isCloudflare = opts.runtime === "cloudflare";

  const pkg = {
    name: opts.name,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      "buna:prepare": "buna prepare --config buna.config.ts",
      dev: "bun run buna:prepare && bun --hot src/entry.ts",
      build:
        "bun run buna:prepare && bun run .buna/build.ts" +
        (isCloudflare ? " --runtime cloudflare" : ""),
      "check-types": "tsc --noEmit",
    },
    catalog: {
      react: DEFAULTS.react,
      "react-dom": DEFAULTS.react,
    },
    dependencies: {
      "bun-plugin-tailwind": DEFAULTS.bunTailwindPlugin,
      react: DEFAULTS.react,
      "react-dom": DEFAULTS.react,
      tailwindcss: DEFAULTS.tailwind,
      bunax: DEFAULTS.bunax,
    } as Record<string, string>,
    devDependencies: {
      "@buna/dev": DEFAULTS.bunaDev,
      "@types/react": DEFAULTS.react,
      "@types/react-dom": DEFAULTS.reactDom,
      "@types/bun": DEFAULTS.typesBun,
      "@cloudflare/workers-types": DEFAULTS.typesWorkers
    } as Record<string, string>,
  };

  if (isCloudflare) {
    (pkg.devDependencies as Record<string, string>).wrangler = "^3.99.0";
  }

  const tsconfig = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "jsx": "react-jsx",
    "strict": true,
    "lib": ["ESNext", "DOM"],
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"],
      "@public/*": ["./public/*"],
      "#buna/*": [".buna/*"],
      "bunax": [".buna/runtime/index.js"],
      "bunax/*": [".buna/runtime/*"]
    }
  },
  "include": ["src", ".buna", "buna.config.ts", "types", "bun-env.d.ts"],
  "exclude": ["dist", "node_modules"]
}
`;

  const bunEnvDts = `// Generated by create-buna-app

declare module "*.svg" {
  const path: \`\${string}.svg\`;
  export default path;
}

declare module "*.module.css" {
  const classes: { readonly [key: string]: string };
  export = classes;
}
`;

  const bunaConfig = `import { defineConfig } from "bunax";

export default defineConfig({
  routesDir: "src/routes",
  outDir: ".buna",
});
`;

  const entryTs = `import { serve } from "bun";
import { routes } from "#buna/routes.generated";
import { handleRequest } from "bunax/runtime";
import config from "@/buna.config";

const server = serve({
  routes,
  development: process.env.NODE_ENV !== "production" && {
    hmr: true,
    console: true,
  },
  fetch(req) {
    const env: any = {};
    const ctx = { waitUntil: (_p: Promise<any>) => {} };
    return handleRequest(req, env, ctx, config);
  },
});

console.log(\`🚀 Server running at \${server.url}\`);
`;

  const layoutTsx = `import "./index.css";
import React from "react";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default Layout;
`;

  const routeTsx = `import { createRoute, type RouteContext } from "bunax";
import { useState } from "react";
import logoUrl from "@public/logo.svg";

const Home = createRoute((ctx: RouteContext) => {
  const [count, setCount] = useState(0);

  return (
    <main className="min-h-screen bg-[#0d0d0d] text-slate-100 flex items-center justify-center px-6">
      <div className="w-full flex justify-center flex-col gap-4 max-w-xl text-center">
        <img src={logoUrl} alt="Buna logo" width={100} className="self-center" />

        <h1 className="text-4xl font-semibold tracking-tight mb-3">
          Welcome to <span className="text-emerald-400">buna()</span>
        </h1>
        <p className="text-slate-400">
          Edit <code className="px-1.5 py-0.5 bg-slate-800 rounded text-emerald-300">src/routes/index.tsx</code> to begin.
        </p>

        <div className="mt-10 border border-slate-700 bg-slate-800/50 rounded-xl p-6 shadow-lg">
          <p className="text-xs uppercase tracking-wider text-slate-400 mb-4">Interactive example</p>
          <div className="flex flex-col gap-4 items-center justify-between">
            <span className="text-3xl font-medium tabular-nums">{count}</span>
            <button
              onClick={() => setCount((prev: number) => prev + 1)}
              className="px-4 py-2 text-sm rounded-lg border border-emerald-400/70 bg-emerald-500/80 text-slate-950 hover:bg-emerald-400 transition cursor-pointer"
            >
              Increment
            </button>
          </div>
          <button
            onClick={() => setCount(0)}
            className="block mx-auto mt-4 text-sm text-slate-400 hover:text-slate-200 transition cursor-pointer"
          >
            Reset
          </button>
        </div>

        <p className="mt-10 text-xs text-slate-500">Built using buna() + Tailwind</p>
      </div>
    </main>
  );
});

Home.meta = {
  title: "Welcome to buna()",
  description: "Starter page for your Buna app.",
  robots: { index: true, follow: true },
};

export default Home;
`;

  const indexCss = `@import "tailwindcss";
`;

  const bunfig = `[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[entrypoints]
server = "src/entry.ts"
`;

  const gitignore = `node_modules
dist
out
*.tgz
coverage
*.lcov
logs
_.log
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
.env
.env.*.local
.eslintcache
.cache
*.tsbuildinfo
.idea
.DS_Store
.buna
.wrangler
`;

  const readme = `# ${opts.name}

A minimal ${opts.runtime === "cloudflare" ? "Cloudflare Worker" : "Bun"} app bootstrapped with buna().

## Quickstart

\`\`\`bash
cd ${opts.name}
bun install
bun run dev
\`\`\`

Then open http://localhost:3000 and edit \`src/routes/index.tsx\`.

## Build

- \`bun run build\` ${isCloudflare
      ? "(builds the Cloudflare worker at .buna/cloudflare)"
      : "(builds your Bun server)"
    }.
- \`bun run buna:prepare\` regenerates .buna helpers (routes + build runner).
- \`bun run check-types\` runs TypeScript without emitting files.
`;



  const wrangler = isCloudflare
    ? `{
  "name": "${opts.name}",
  "main": ".buna/cloudflare/worker.js",
  "compatibility_date": "2024-05-01",
  "observability": { "enabled": true },
  "assets": { "binding": "ASSETS", "directory": ".buna/cloudflare/assets", "run_worker_first": false },
  "compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"]
}
`
    : null;

  const files: Record<string, string> = {
    "package.json": JSON.stringify(pkg, null, 2) + "\n",
    "tsconfig.json": tsconfig,
    "buna.config.ts": bunaConfig,
    "bunfig.toml": bunfig,
    ".gitignore": gitignore,
    "bun-env.d.ts": bunEnvDts,
    "README.md": readme,
    "public/logo.svg": logoSvg,
    "src/entry.ts": entryTs,
    "src/index.css": indexCss,
    "src/layout.tsx": layoutTsx,
    "src/routes/index.tsx": routeTsx,
  };

  if (wrangler) {
    files["wrangler.json"] = wrangler;
  }

  return files;
}
