// AUTO-GENERATED BY buna-plugin.
// Basic CRUD Hono module for "admin"

import { Hono } from 'hono';
import * as adminService from '../services/admin.service';

const adminModule = new Hono();

// GET /admin
adminModule.get('/', async (c) => {
  const items = await adminService.listAdmins();
  return c.json({ data: items });
});

// GET /admin/:id
adminModule.get('/:id', async (c) => {
  const id = c.req.param('id');
  const item = await adminService.getAdminById(id);
  if (!item) {
    return c.json({ error: 'Admin not found' }, 404);
  }
  return c.json({ data: item });
});

// POST /admin
adminModule.post('/', async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const created = await adminService.createAdmin(body);
  return c.json({ data: created }, 201);
});

// PUT /admin/:id
adminModule.put('/:id', async (c) => {
  const id = c.req.param('id');
  const body = await c.req.json().catch(() => ({}));
  const updated = await adminService.updateAdmin(id, body);
  if (!updated) {
    return c.json({ error: 'Admin not found' }, 404);
  }
  return c.json({ data: updated });
});

// DELETE /admin/:id
adminModule.delete('/:id', async (c) => {
  const id = c.req.param('id');
  const ok = await adminService.deleteAdmin(id);
  if (!ok) {
    return c.json({ error: 'Admin not found' }, 404);
  }
  return c.json({ ok: true });
});

export default adminModule;
