// AUTO-GENERATED BY buna-plugin.
// Basic CRUD Hono module for "users"

import { Hono } from 'hono';
import * as usersService from '../services/users.service';

const usersModule = new Hono();

// GET /users
usersModule.get('/', async (c) => {
  const items = await usersService.listUsers();
  return c.json({ data: items });
});

// GET /users/:id
usersModule.get('/:id', async (c) => {
  const id = c.req.param('id');
  const item = await usersService.getUserById(id);
  if (!item) {
    return c.json({ error: 'User not found' }, 404);
  }
  return c.json({ data: item });
});

// POST /users
usersModule.post('/', async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const created = await usersService.createUser(body);
  return c.json({ data: created }, 201);
});

// PUT /users/:id
usersModule.put('/:id', async (c) => {
  const id = c.req.param('id');
  const body = await c.req.json().catch(() => ({}));
  const updated = await usersService.updateUser(id, body);
  if (!updated) {
    return c.json({ error: 'User not found' }, 404);
  }
  return c.json({ data: updated });
});

// DELETE /users/:id
usersModule.delete('/:id', async (c) => {
  const id = c.req.param('id');
  const ok = await usersService.deleteUser(id);
  if (!ok) {
    return c.json({ error: 'User not found' }, 404);
  }
  return c.json({ ok: true });
});

export default usersModule;
