// AUTO-GENERATED BY buna-plugin.
// You can freely edit this file.

export type Admin = {
  id: string;
  // TODO: add more fields here
};

let admin: Admin[] = [];

export async function listAdmins(): Promise<Admin[]> {
  return admin;
}

export async function getAdminById(id: string): Promise<Admin | null> {
  return admin.find((item) => item.id === id) ?? null;
}

export async function createAdmin(data: Partial<Admin>): Promise<Admin> {
  const item: Admin = {
    id: String(Date.now()),
    ...data,
  } as Admin;

  admin.push(item);
  return item;
}

export async function updateAdmin(id: string, data: Partial<Admin>): Promise<Admin | null> {
  const index = admin.findIndex((item) => item.id === id);
  if (index === -1) return null;

  const updated = { ...admin[index], ...data } as Admin;
  admin[index] = updated;
  return updated;
}

export async function deleteAdmin(id: string): Promise<boolean> {
  const before = admin.length;
  admin = admin.filter((item) => item.id !== id);
  return admin.length < before;
}
