// AUTO-GENERATED BY buna-plugin.
// You can freely edit this file.

export type User = {
  id: string;
  // TODO: add more fields here
};

let users: User[] = [];

export async function listUsers(): Promise<User[]> {
  return users;
}

export async function getUserById(id: string): Promise<User | null> {
  return users.find((item) => item.id === id) ?? null;
}

export async function createUser(data: Partial<User>): Promise<User> {
  const item: User = {
    id: String(Date.now()),
    ...data,
  } as User;

  users.push(item);
  return item;
}

export async function updateUser(id: string, data: Partial<User>): Promise<User | null> {
  const index = users.findIndex((item) => item.id === id);
  if (index === -1) return null;

  const updated = { ...users[index], ...data } as User;
  users[index] = updated;
  return updated;
}

export async function deleteUser(id: string): Promise<boolean> {
  const before = users.length;
  users = users.filter((item) => item.id !== id);
  return users.length < before;
}
